<?php

namespace AppBundle\Repository;

/**
 * JeuxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JeuxRepository extends \Doctrine\ORM\EntityRepository
{
}
