<?php

namespace AppBundle\Repository;

/**
 * PersonnagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonnagesRepository extends \Doctrine\ORM\EntityRepository
{
}
